packages:
  - packages/*
  - website
  - dev/*
  - rust/rotext_wasm_bindings/pkg

catalog:
  '@codemirror/state': ^6.4.1
  '@codemirror/theme-one-dark': ^6.1.2
  '@dicexp/interface': ^0.5.0
  '@dicexp/naive-evaluator': ^0.6.2
  '@dicexp/naive-evaluator-builtins': ^0.5.0
  '@dicexp/naive-evaluator-in-worker': ^0.5.3
  '@dicexp/solid-components': ^0.3.0
  '@rolludejo/internal-web-shared': ^0.4.1
  '@rollup/plugin-node-resolve': ^15.3.0
  '@rollup/plugin-typescript': ^12.1.1
  '@solid-primitives/media': ^2.2.9
  '@solid-primitives/storage': ^4.3.1
  '@solidjs/router': ^0.15.1
  '@tailwindcss/typography': ^0.5.16
  '@tailwindcss/vite': ^4.0.12
  codemirror: ^6.0.1
  concurrently: ^9.1.0
  daisyui: ^5.0.0
  hast-util-format: ^1.1.0
  hast-util-from-html: ^2.0.3
  hast-util-to-html: ^9.0.3
  html-validate: ^8.25.0
  idiomorph: ^0.3.0
  jsdom: ^25.0.1
  node-html-parser: ^6.1.13
  rollup: ^4.26.0
  rollup-plugin-delete: ^2.1.0
  rollup-plugin-dts: ^6.1.1
  sass: ^1.80.7
  sass-embedded: ^1.80.7
  solid-devtools: ^0.30.1
  solid-element: ^1.9.1
  solid-icons: ^1.1.0
  solid-js: ^1.9.3
  tailwindcss: ^4.0.12
  tslib: ^2.8.1
  typescript: ^5.6.3
  vite: ^6.2.1
  vite-node: ^2.1.5
  vite-plugin-dts: ^4.5.3
  vite-plugin-solid: ^2.10.2
  vitest: ^2.1.5
  yaml: ^2.6.0
  zod: ^3.23.8

catalogMode: strict
