packages:
  - packages/*
  - website
  - dev/*
  - rust/rotext_wasm_bindings/pkg

catalog:
  '@codemirror/state': ^6.5.2
  '@codemirror/theme-one-dark': ^6.1.3
  '@dicexp/interface': ^0.5.0
  '@dicexp/naive-evaluator': ^0.6.2
  '@dicexp/naive-evaluator-builtins': ^0.5.0
  '@dicexp/naive-evaluator-in-worker': ^0.5.3
  '@dicexp/solid-components': ^0.3.0
  '@rolludejo/internal-web-shared': ^0.4.1
  '@rollup/plugin-node-resolve': ^16.0.1
  '@rollup/plugin-typescript': ^12.1.4
  '@solid-primitives/media': ^2.3.3
  '@solid-primitives/storage': ^4.3.3
  '@solidjs/router': ^0.15.3
  '@tailwindcss/typography': ^0.5.16
  '@tailwindcss/vite': ^4.1.13
  '@types/node': ^24.3.1
  codemirror: ^6.0.2
  concurrently: ^9.2.1
  daisyui: ^5.1.10
  hast-util-format: ^1.1.0
  hast-util-from-html: ^2.0.3
  hast-util-to-html: ^9.0.5
  html-validate: ^10.0.0
  idiomorph: ^0.7.3
  jsdom: ^26.1.0
  node-html-parser: ^7.0.1
  rollup: ^4.50.1
  rollup-plugin-delete: ^3.0.1
  rollup-plugin-dts: ^6.2.3
  sass: ^1.92.1
  sass-embedded: ^1.92.1
  solid-devtools: ^0.34.3
  solid-element: ^1.9.1
  solid-icons: ^1.1.0
  solid-js: ^1.9.9
  tailwindcss: ^4.1.13
  tslib: ^2.8.1
  typescript: ^5.9.2
  vite: ^7.1.5
  vite-node: ^3.2.4
  vite-plugin-dts: ^4.5.4
  vite-plugin-solid: ^2.11.8
  vitest: ^3.2.4
  yaml: ^2.8.1
  zod: ^4.1.5

catalogMode: strict
