set fallback

build-rotext: build-rotext-wasm-bindings
build-rotext-dev: build-rotext-wasm-bindings-dev

build-rotext-wasm-bindings:
	cd rotext_wasm_bindings && wasm-pack build --target web
build-rotext-wasm-bindings-dev:
	cd rotext_wasm_bindings && wasm-pack build --target web --dev