set fallback

prepare:
	just parsing build
	just build-rotext
	just build-doc-syntax-reference

dev: prepare
	pnpm run dev

build: prepare build-doc-syntax-reference
	pnpm run build

build-doc-syntax-reference:
	pnpm run build:doc-syntax-reference