set fallback

prepare:
	just build-doc-syntax-reference
	just legacy-parsing build
	just build-rotext

dev: prepare
	pnpm run dev

build: prepare build-doc-syntax-reference
	pnpm run build

build-doc-syntax-reference:
	pnpm run build:doc-syntax-reference