set fallback

prepare:
	just build-rotext
	just build-wiki
	just build-solid-components

dev: prepare
	pnpm run dev

build: prepare
	pnpm run build

WIKI_INPUT := "../docs/wiki/"
WIKI_OUTPUT := "./public/static/generated/wiki"

build-wiki:
	rm -rf {{WIKI_OUTPUT}}
	mkdir -p {{WIKI_OUTPUT}}
	pnpm exec vite-node ../scripts/wiki-builder/src/main.ts -i {{WIKI_INPUT}} -o {{WIKI_OUTPUT}}