name: 测试-rust

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [none, all]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Just
        uses: extractions/setup-just@v1

      - name: Setup Rust
        run: |
            rustup toolchain install nightly-2024-07-26 --profile minimal
            rustup default nightly-2024-07-26
            rustup component add clippy

      - name: Run tests without features
        if: matrix.features == 'none'
        run: |
          cd rust/rotext && just test

      - name: Run tests with all features
        if: matrix.features == 'all'
        run: |
          cd rust/rotext && just test-af